artifact_location: file:///c:/code/quant-v1/quant-train-v1/mlflow/794404334221073423
creation_time: 1781784498345
effective_trace_archival_retention: null
experiment_id: '794404334221073423'
last_update_time: 1781784498345
lifecycle_stage: active
name: XAUUSD_H1_mean_reverting
trace_location: null
workspace: default
