artifact_location: file:///c:/code/quant-v1/quant-train-v1/mlflow/174334908859131551
creation_time: 1781782943288
effective_trace_archival_retention: null
experiment_id: '174334908859131551'
last_update_time: 1781784360793
lifecycle_stage: active
name: XAUUSD_H1_bear_trend
tags: {}
trace_location: null
workspace: default
