artifact_uri: file:///c:/code/quant-v1/quant-train-v1/mlruns/295131167266714025/fec9a9fdebc5484eb22e943819bb362b/artifacts
end_time: 1781767673789
entry_point_name: ''
experiment_id: '295131167266714025'
lifecycle_stage: active
run_id: fec9a9fdebc5484eb22e943819bb362b
run_name: Optuna_Auto_Tuning
source_name: ''
source_type: 4
source_version: ''
start_time: 1781767673526
status: 3
tags: []
user_id: lumba
